// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSoRplr4vKqxagq1f0aSXjEEiGJcBTrsg',
    appId: '1:549509831402:web:a524ed12782e09d3ec5593',
    messagingSenderId: '549509831402',
    projectId: 'taskaholics',
    authDomain: 'taskaholics.firebaseapp.com',
    storageBucket: 'taskaholics.firebasestorage.app',
    measurementId: 'G-DRH938D0X4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWfZJwpbLU3g9Yz_JAYvuU2UCINFtaR2g',
    appId: '1:549509831402:android:21f3d1cbd729165dec5593',
    messagingSenderId: '549509831402',
    projectId: 'taskaholics',
    storageBucket: 'taskaholics.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPRMh99F878KtlFk-VQ7k4wpVKtkQub0Y',
    appId: '1:549509831402:ios:550bd7df2b160a76ec5593',
    messagingSenderId: '549509831402',
    projectId: 'taskaholics',
    storageBucket: 'taskaholics.firebasestorage.app',
    iosBundleId: 'com.example.taskaholic',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPRMh99F878KtlFk-VQ7k4wpVKtkQub0Y',
    appId: '1:549509831402:ios:550bd7df2b160a76ec5593',
    messagingSenderId: '549509831402',
    projectId: 'taskaholics',
    storageBucket: 'taskaholics.firebasestorage.app',
    iosBundleId: 'com.example.taskaholic',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCSoRplr4vKqxagq1f0aSXjEEiGJcBTrsg',
    appId: '1:549509831402:web:cc38d37c86938f77ec5593',
    messagingSenderId: '549509831402',
    projectId: 'taskaholics',
    authDomain: 'taskaholics.firebaseapp.com',
    storageBucket: 'taskaholics.firebasestorage.app',
    measurementId: 'G-RBM0F42C5B',
  );
}
