// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDU6_-tRiWokpEb2372cf1UTVtLBYL1qv0',
    appId: '1:770782639935:web:bfec9865d1a02a5be7c58a',
    messagingSenderId: '770782639935',
    projectId: 'taskaholic-24a23',
    authDomain: 'taskaholic-24a23.firebaseapp.com',
    storageBucket: 'taskaholic-24a23.firebasestorage.app',
    measurementId: 'G-MEASUREMENT_ID',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDU6_-tRiWokpEb2372cf1UTVtLBYL1qv0',
    appId: '1:770782639935:android:bfec9865d1a02a5be7c58a',
    messagingSenderId: '770782639935',
    projectId: 'taskaholic-24a23',
    storageBucket: 'taskaholic-24a23.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDU6_-tRiWokpEb2372cf1UTVtLBYL1qv0',
    appId: '1:770782639935:ios:bfec9865d1a02a5be7c58a',
    messagingSenderId: '770782639935',
    projectId: 'taskaholic-24a23',
    storageBucket: 'taskaholic-24a23.firebasestorage.app',
    iosBundleId: 'com.example.todoList',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDU6_-tRiWokpEb2372cf1UTVtLBYL1qv0',
    appId: '1:770782639935:ios:bfec9865d1a02a5be7c58a',
    messagingSenderId: '770782639935',
    projectId: 'taskaholic-24a23',
    storageBucket: 'taskaholic-24a23.firebasestorage.app',
    iosBundleId: 'com.example.todoList',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDU6_-tRiWokpEb2372cf1UTVtLBYL1qv0',
    appId: '1:770782639935:windows:bfec9865d1a02a5be7c58a',
    messagingSenderId: '770782639935',
    projectId: 'taskaholic-24a23',
    storageBucket: 'taskaholic-24a23.firebasestorage.app',
  );
}
